services:
  app_inventory_management:
    build: 
      context: ./inventory_management
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://dpg-d00svb24d50c73cktbn0-a.ohio-postgres.render.com:5432/inventory_db_n6xl?sslmode=require
      DB_USERNAME: inventory_db_n6xl_user
      DB_PASSWORD: 5BsWJUfy8WgRsEBl1sd6EjLIz8F00Hsp
    restart: always